version: '3.8'

services:
  ollama:
    image: ollama_image
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    environment:
      OLLAMA_CONFIG: ${OLLAMA_CONFIG}
    depends_on:
      - postgres

  lm_studio:
    image: lm